bio_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    # path('',include('tugas.urls')),
]

contact_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    
    # path('',include('tugas.urls')),
]

education_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    
    # path('',include('tugas.urls')),
]

extra_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    
    # path('',include('tugas.urls')),
]

schedule_page/urls.py
from django.urls import path
from . import views

app_name = 'schedule_page'

urlpatterns = [
    path('',views.schedule_page,name='schedule'),
    path('create/',views.create,name='create'),
    path('delete/<int:id_delete>',views.delete,name='delete'),
    # path('',include('tugas.urls')),
]

tugas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='index'),
]

web-ludy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls')),
    path('bio/',include('bio_page.urls')),
    path('education/',include('education_page.urls')),
    path('contact/',include('contact_page.urls')),
    path('extra/',include('extra_page.urls')),
    path('schedule/',include('schedule_page.urls')),
]

bio_page/models.py
from django.db import models

# Create your models here.

contact_page/models.py
from django.db import models

# Create your models here.

education_page/models.py
from django.db import models

# Create your models here.

extra_page/models.py
from django.db import models

# Create your models here.

schedule_page/models.py
from django.db import models

DAY = [
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
    ('Sunday', 'Sunday'),
]

# Create your models here.
class Activity(models.Model):
    activity = models.CharField(max_length = 20)
    category = models.CharField(max_length = 20)
    place = models.CharField(max_length = 20)
    # date_time = models.DateTimeField()
    date = models.DateField()
    time = models.TimeField()
    day = models.CharField(max_length = 9, choices = DAY)

    def __str__(self):
        return "{}".format(self.activity) 

tugas/models.py
from django.db import models

# Create your models here.

schedule_page/forms.py
from django import forms

from .models import Activity


class Input_Form(forms.ModelForm):
    # activity = forms.CharField(widget = forms.TextInput({'class':'form'}))
    # category = forms.CharField(widget = forms.TextInput({'class':'form'}))
    # place = forms.CharField(widget = forms.TextInput({'class':'form'}))
    # date_time = forms.DateTimeField(widget =  forms.DateTimeInput({'class':'form'}))
    # date = forms.DateField(widget = forms.DateInput({'class':'form'}))
    # time = forms.TimeField(widget = forms.TimeInput({'class':'form'}))
    # day = forms.CharField(widget = forms.TextInput({'class':'form'}))
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'activity' : forms.TextInput(
                attrs = {
                    'class' : 'form-control'
                }
            ),

            'category' : forms.TextInput(
                attrs = {
                    'class' : 'form-control'
                }
            ),

            'place' : forms.TextInput(
                attrs = {
                    'class' : 'form-control'
                }
            ),

            'date' : forms.SelectDateWidget(
                attrs = {
                    'class' : 'form-control'
                }
            ),

            'time' : forms.TimeInput(
                attrs = {
                    'type' : 'time',
                    'class' : 'form-control'
                }
            ),

        }

tugas/forms.py
from django import forms

##Create your forms here

bio_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'pages/bio_page.html',{})

contact_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'pages/contact_page.html',{})

education_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'pages/education_page.html',{})

extra_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'pages/extra_page.html',{})

schedule_page/views.py
from django.shortcuts import render, redirect
from .models import Activity
from .forms import Input_Form

# Create your views here.


def schedule_page(request):
    activity = Activity.objects.all()

    response = {
        # 'form' : Input_Form(),
        'activity' : activity
    }

    return render(request, 'pages/schedule_page.html', response)


def create(request):
    form = Input_Form(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('schedule_page:schedule')

    response = {
        'form' : form
    }

    return render(request, 'pages/filling_page.html', response)


def delete(request, id_delete):
    Activity.objects.filter(id = id_delete).delete()
    return redirect('schedule_page:schedule')

tugas/views.py
from django.shortcuts import render,redirect

# Create your views here.
def home(request):
    return render(request,'pages/index.html',{})

bio_page/templates/pages/bio_page.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- kalo pake cdn -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="{%static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{%static "css/style.css" %}">
    <title>Ludy's Web - Bio Page</title>
</head>

<body>
    <div class="d-flex bd-highlight mb-3">
        <div class="mr-auto p-2 bd-highlight">
            <a href="/"><img src="{%static "assets/web_logo.png" %}" alt="Logo" width="70px"></a>
        </div>
        <div class="hide-mobile mr-auto p-2 bd-highlight">
            <h3 class="bio-title">My Bio</h3>
        </div>
        <div class="drop-pos p-2 bd-highlight">
            {%include "pages/dropdown.html"%}
        </div>
    </div>

    <div class="show-mobile" style="text-align: center">
        <h3 class="bio-title">My Bio</h3>
    </div>
    <div class="row bio-positioning">
        <div class="col-sm-3 photo-position">
            <a href="https://quanta2018.com/Biodata/detail.html?absen=201"><img src="{%static "assets/bio-photo.png" %}"
                    alt="My Photo" width="270px;"></a>
        </div>

        <div class="col-sm-5 bio-box">
            <div class="border-bio">
                <div class="text-align hide-mobile">
                    <div class="text-var clr-darkblue bold-font">
                        Name <br> Birth Date <br> Hobby
                    </div>
                    <div class="colon clr-darkblue bold-font">
                        : <br> : <br> :
                    </div>
                    <div class="text-val clr-black bold-font">
                        Abdurrahman Luqmanul H. (Ludy) <br> June 3 2000 <br> Playing Games and Sleeping
                    </div>
                </div>
                <div class="show-mobile" style="color: black; font-weight: bold">
                    <spam class="clr-darkblue">Name :</spam><br>Abdurrahman Luqmanul Hakim
                    <br>
                    <spam class="clr-darkblue">Birth Date :</spam><br>June 3 2000
                    <br>
                    <spam class="clr-darkblue">Hobby :</spam><br>Playing Games and Sleeping
                </div>
                <div class="desc">
                    <div class="clr-darkblue bold-font">Description about Myself : <br></div>
                    <div class="clr-black bold-font"> Hello, my name is Abdurrahman Luqmanul Hakim, but
                        people call me Ludy. Im a student at Faculty of Computer Science. Im currently a student at
                        University of Indonesia. I really love playing video games, often resulting in my bad grades and
                        lack of sleep.</divclass>
                    </div>
                </div>

            </div>
        </div>

        <div class="col-sm-4 skill-position">
            <div class="skill-box">
                <div class="clr-darkblue">My Skills</div>
                <div class="clr-white">- Python basic knowledge <br>
                    - Java basic knowledge <br>
                    - HTML & CSS basic knowledge</div>
            </div>
        </div>
    </div>

    <div class="footer">
        <div class="d-flex flex-row">
            <div class="p-2"><a href="/">
                    <h4 class="res-footer clr-lightblue">Home</h4>
                </a></div>
            <div class="p-2">
                <h4 class="res-footer selected">Bio</h4>
            </div>
            <div class="p-2"><a href="/education">
                    <h4 class="res-footer clr-lightblue">Education</h4>
                </a></div>
            <div class="p-2"><a href="/contact">
                    <h4 class="res-footer clr-lightblue">Contact</h4>
                </a></div>
            <div class="p-2"><a href="/schedule">
                    <h4 class="res-footer clr-lightblue">Schedule</h4>
                </a></div>
            <div class="p-2"><a href="/extra">
                    <h4 class="res-footer clr-lightblue">Extra</h4>
                </a></div>
        </div>
    </div>

    <!-- kalau pakai cdn -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->

    <script src="{%static "bootstrap/js/jquery.js" %}"></script>
    <script src="{%static "bootstrap/js/popper.js" %}"></script>
    <script src="{%static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>

</html>

contact_page/templates/pages/contact_page.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- kalo pake cdn -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="{%static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{%static "css/style.css" %}">
    <title>Ludy's Web - Contact Page</title>
</head>

<body>
    <div class="d-flex bd-highlight mb-3">
        <div class="mr-auto p-2 bd-highlight">
            <a href="/"><img src="{%static "assets/web_logo.png" %}" alt="Logo" width="70px"></a>
        </div>
        <div class="drop-pos p-2 bd-highlight">
            <h5 class="bold-font">
                {%include "pages/dropdown.html"%}
        </div>
    </div>

    <div class="contact-struc">
        <div class="padding-cont">
            <h3 class="contact-underline clr-darkblue">You can contact me at:</h3>
        </div>

        <div class="contact-align">
            <div class="contact-left"></div>
            <div class="contact-var clr-darkblue">
                <h4 class="font-shrink">
                    <br>Email<br>
                    <br>HP<br>
                    <br>Line<br>
                    <br>Gitlab<br>
                    <br>Github</h4>
            </div>
            <div class="contact-mid clr-darkblue">
                <h4 class="font-shrink"><br> : <br><br> : <br><br> : <br><br> : <br><br> : </h4>
            </div>
            <div class="contact-val">
                <h4 class="font-shrink"><br> Ludyaldy@gmail.com<br>
                    <br> 08118020004<br>
                    <br> Ludyluqmanhakim<br>
                    <br> https://gitlab.com/AndiALH<br>
                    <br> https://github.com/AndiALH
                </h4>
            </div>
            <div class="contact-right"></div>
        </div>

        <div class=img-align style="padding-top: 40px;">
            <div class="img-left"></div>
            <div class="img-mid">
                <a href="https://www.facebook.com/ludyALH"><img src="{%static "assets/fb_icon.png" %}"
                        alt="Facebook icon" class="contact-img"></a>
                <span style="display:inline-block; width: 100px;"></span>
                <a href="https://www.instagram.com/andiluqmanh/"><img src="{%static "assets/ig_icon.png" %}"
                        alt="Instagram icon" class="contact-img"></a>
                <span style="display:inline-block; width: 100px;"></span>
                <a href="https://www.linkedin.com/in/abdurrahman-l-201663113/"><img
                        src="{%static "assets/lin_icon.png" %}" alt="LinkedIn icon" class="contact-img"></a>
            </div>
            <div class="img-right"></div>
        </div>
    </div>

    <div class="footer">
        <div class="d-flex flex-row">
            <div class="p-2"><a href="/">
                    <h4 class="res-footer clr-lightblue">Home</h4>
                </a></div>
            <div class="p-2"><a href="/bio">
                    <h4 class="res-footer clr-lightblue">Bio</h4>
                </a></div>
            <div class="p-2"><a href="/education">
                    <h4 class="res-footer clr-lightblue">Education</h4>
                </a></div>
            <div class="p-2">
                <h4 class="res-footer selected">Contact</h4>
            </div>
            <div class="p-2"><a href="/schedule">
                    <h4 class="res-footer clr-lightblue">Schedule</h4>
                </a></div>
            <div class="p-2"><a href="/extra">
                    <h4 class="res-footer clr-lightblue">Extra</h4>
                </a></div>
        </div>
    </div>

    <!-- kalau pakai cdn -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->

    <script src="{%static "bootstrap/js/jquery.js" %}"></script>
    <script src="{%static "bootstrap/js/popper.js" %}"></script>
    <script src="{%static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>

</html>

education_page/templates/pages/education_page.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- kalo pake cdn -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="{%static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{%static "css/style.css" %}">
    <title>Ludy's Web - Education Page</title>
</head>

<body>
    <div class="d-flex bd-highlight mb-3">
        <div class="mr-auto p-2 bd-highlight">
            <a href="/"><img src="{%static "assets/web_logo.png" %}" alt="Logo" width="70px"></a>
        </div>
        <div class="drop-pos p-2 bd-highlight">
            {%include "pages/dropdown.html"%}
        </div>
    </div>

    <div class="edu-line">
        <div class="edu-box">
            <h3 class="clr-darkblue">Education</h3>
        </div>
    </div>

    <div class="edu-data hide-mobile">
        <div class="year-pos clr-darkblue bold-font" style="font-size: 20px">
            <img src="{%static "assets/dot-yline_blue.png" %}" alt="dot line (blue)" class="dotyline-resize"><br>
            2006 - 2012<br>
            <img src="{%static "assets/yline_blue.png" %}" alt="line (blue)" class="yline-resize"><br>
            2012 - 2015<br>
            <img src="{%static "assets/yline_blue.png" %}" alt="line (blue)" class="yline-resize"><br>
            2015 - 2018<br>
            <img src="{%static "assets/yline_blue.png" %}" alt="line (blue)" class="yline-resize"><br>
            <h4 class="underline-blue bold-font">2018 - present</h4>
        </div>
        <div class="line-pos">
            <img src="{%static "assets/dot-yline_white.png" %}" alt="dot line (white)" class="dotyline-resize"><br>
            <img src="{%static "assets/xline_blue.png" %}" alt="line (blue)" class="xline-resize"><br>
            <img src="{%static "assets/yline_white.png" %}" alt="line (white)" class="yline-resize"><br>
            <img src="{%static "assets/xline_blue.png" %}" alt="line (blue)" class="xline-resize"><br>
            <img src="{%static "assets/yline_white.png" %}" alt="line (white)" class="yline-resize"><br>
            <img src="{%static "assets/xline_blue.png" %}" alt="line (blue)" class="xline-resize"><br>
            <img src="{%static "assets/yline_white.png" %}" alt="line (white)" class="yline-resize"><br>
            <img src="{%static "assets/xline_blue.png" %}" alt="line (blue)" class="xline-resize-big">
        </div>
        <div class="school-pos clr-lightblue bold-font" style="font-size: 20px">
            <img src="{%static "assets/dot-yline_white.png" %}" alt="dot line (white)" class="dotyline-resize"><br>
            SD Putra 1 Jakarta<br>
            <img src="{%static "assets/yline_white.png" %}" alt="line (white)" class="yline-resize"><br>
            SMP Putra 1 Jakarta<br>
            <img src="{%static "assets/yline_white.png" %}" alt="line (white)" class="yline-resize"><br>
            SMAN 8 Jakarta<br>
            <img src="{%static "assets/yline_white.png" %}" alt="line (white)" class="yline-resize"><br>
            <h4 class="bold-font">Faculty of Computer Science, University of Indonesia</h4>
        </div>
    </div>

    <div class="show-mobile mobile-edu clr-lightblue bold-font">
        <img src="{%static "assets/dot-yline_blue.png" %}" alt="dot line (blue)" class="dotyline-resize"><br>
        <spam class="clr-darkblue">2006 - 2012</spam><br>SD Putra 1 Jakarta<br>
        <img src="{%static "assets/yline_blue.png" %}" alt="line (blue)" class="yline-resize"><br>
        <spam class="clr-darkblue">2012 - 2015</spam><br>SMP Putra 1 Jakarta<br>
        <img src="{%static "assets/yline_blue.png" %}" alt="line (blue)" class="yline-resize"><br>
        <spam class="clr-darkblue">2015 - 2018</spam><br>SMAN 8 Jakarta<br>
        <img src="{%static "assets/yline_blue.png" %}" alt="line (blue)" class="yline-resize"><br>
        <spam class="clr-darkblue">2018 - present</spam><br>Faculty of Computer Science, University of Indonesia
    </div>

    <div class="footer">
        <div class="d-flex flex-row">
            <div class="p-2"><a href="/">
                    <h4 class="res-footer clr-lightblue">Home</h4>
                </a></div>
            <div class="p-2"><a href="/bio">
                    <h4 class="res-footer clr-lightblue">Bio</h4>
                </a></div>
            <div class="p-2">
                <h4 class="res-footer selected">Education</h4>
            </div>
            <div class="p-2"><a href="/contact">
                    <h4 class="res-footer clr-lightblue">Contact</h4>
                </a></div>
            <div class="p-2"><a href="/schedule">
                    <h4 class="res-footer clr-lightblue">Schedule</h4>
                </a></div>
            <div class="p-2"><a href="/extra">
                    <h4 class="res-footer clr-lightblue">Extra</h4>
                </a></div>
        </div>
    </div>

    <!-- kalau pakai cdn -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->

    <script src="{%static "bootstrap/js/jquery.js" %}"></script>
    <script src="{%static "bootstrap/js/popper.js" %}"></script>
    <script src="{%static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>

</html>

schedule_page/templates/pages/schedule_page.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- kalo pake cdn -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="{%static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{%static "css/style.css" %}">
    <title>Ludy's Web - Schedule Page</title>
</head>

<body>
    <div class="d-flex bd-highlight mb-3">
        <div class="mr-auto p-2 bd-highlight">
            <a href="/"><img src="{%static "assets/web_logo.png" %}" alt="Logo" width="70px"></a>
        </div>
        <div class="drop-pos p-2 bd-highlight">
            <h5 class="bold-font">
                {%include "pages/dropdown.html"%}
        </div>
    </div>

    <div class="schedule-title">My Schedule</div>

    <div class="add-button">
        <a href="{% url 'schedule_page:create' %}" class="btn-edit btn btn-primary"
            style="background-color: aliceblue; color: #5AA6FF">Add</a>
    </div>
    <div class="table-height">
        <table class="table table-blue">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th class="mobile-width" scope="col">Activity</th>
                    <th class="hide-mobile" scope="col">Category</th>
                    <th class="mobile-width" scope="col">Place</th>
                    <th scope="col">Date</th>
                    <th scope="col">Time</th>
                    <th class="hide-mobile" scope="col">Day</th>
                    <th scope="col"> X</th>
                </tr>
            </thead>
            <tbody>
                {% for post in activity %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td class="mobile-width">{{post.activity}}</td>
                    <td class="hide-mobile">{{post.category}}</td>
                    <td class="mobile-width">{{post.place}}</td>
                    <td>{{post.date}}</td>
                    <td>{{post.time}}</td>
                    <td class="hide-mobile">{{post.day}}</td>
                    <td class="hide-mobile"><a href="{% url 'schedule_page:delete' post.id %}"
                            class="outline-edit btn-outline-primary">remove</a>
                    </td>
                    <td class="show-mobile"><a href="{% url 'schedule_page:delete' post.id %}"
                            class="outline-edit btn-outline-primary">X</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    <div class="footer">
        <div class="d-flex flex-row">
            <div class="p-2"><a href="/">
                    <h4 class="res-footer clr-lightblue">Home</h4>
                </a></div>
            <div class="p-2"><a href="/bio">
                    <h4 class="res-footer clr-lightblue">Bio</h4>
                </a></div>
            <div class="p-2"><a href="/education">
                    <h4 class="res-footer clr-lightblue">Education</h4>
                </a></div>
            <div class="p-2"><a href="/contact">
                    <h4 class="res-footer clr-lightblue">Contact</h4>
                </a></div>
            <div class="p-2">
                <h4 class="res-footer selected">Schedule</h4>
            </div>
            <div class="p-2"><a href="/extra">
                    <h4 class="res-footer clr-lightblue">Extra</h4>
                </a></div>
        </div>
    </div>

    <!-- kalau pakai cdn -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->

    <script src="{%static "bootstrap/js/jquery.js" %}"></script>
    <script src="{%static "bootstrap/js/popper.js" %}"></script>
    <script src="{%static "bootstrap/js/bootstrap.min.js" %}"></script>
</body>

</html>